version: '3.4'

services:
  blogapp:
    image: ${DOCKER_REGISTRY-}blogapp
    build:
      context: .
      dockerfile: BlogApp/Dockerfile

  blogapp.api:
    image: ${DOCKER_REGISTRY-}blogapp
    build:
      context: .
      dockerfile: BlogApp/Dockerfile


